import mysql from 'mysql2/promise';

const url = process.env.DATABASE_URL;
if (!url) throw new Error('DATABASE_URL is missing');

const connection = await mysql.createConnection(url);

const moveId = 60028;

const groups = [
  {
    name: 'full_update_like_runtime_payload',
    sql: `UPDATE moves SET
      moveCode = ?,
      pickupAddress = ?,
      pickupFloor = ?,
      pickupElevatorCapacity = ?,
      pickupParkingDistance = ?,
      deliveryAddress = ?,
      deliveryFloor = ?,
      deliveryElevatorCapacity = ?,
      deliveryParkingDistance = ?,
      pickupDate = ?,
      deliveryDate = ?,
      volume = ?,
      grossPrice = ?,
      distance = ?,
      moveType = ?,
      anfahrt = ?,
      servicesjson = ?,
      summary = ?,
      anmerkungen = ?,
      serviceanmerkungen = ?,
      moebelliste = ?,
      kundennote = ?,
      kontaktinfo = ?,
      zahlungsart = ?,
      rechnungnr = ?,
      bewertungplatform = ?,
      bewertunglink = ?,
      planstartzeit = ?,
      planendzeit = ?,
      planbemerkungen = ?,
      schadenstatus = ?,
      beschwerdeschweregrad = ?,
      extrabemerkungen = ?,
      status = ?,
      paymentStatus = ?,
      schaden_description = ?,
      beschwerde_description = ?,
      bezahlt_von = ?,
      betzhalkunde = ?,
      ist_bezahlt = ?,
      payment_way = ?,
      audit_total_price = ?,
      bank_betrag = ?,
      bar_betrag = ?,
      rechnung_ausgestellt = ?,
      rechnung_betrag = ?,
      rechnung_nummer = ?,
      updatedAt = NOW()
      WHERE id = ?`,
    params: [
      '60022',
      'Dorneburger str 1',
      '1.Etage',
      'Aufzug klein',
      '40 - 50 m',
      '24 Im Lörenkamp',
      '1.Etage',
      'Aufzug klein',
      '10 - 20 m',
      '2026-04-18 00:00:00',
      '2026-04-29 00:00:00',
      79,
      2500,
      400,
      'Umzug',
      0,
      '{"einpackservice":false,"einpackKartons":"0","abbauMoebeln":false,"abbauMoebelnM3":"0","abbauKueche":false,"abbauKuecheM3":"0","parkzoneAuszug":true,"auspackservice":false,"auspackKartons":"0","aufbauMoebeln":false,"aufbauMoebelnM3":"0","aufbauKueche":false,"aufbauKuecheM3":"0","parkzoneEinzug":true,"umzugskartons":"34","kleiderkartons":"34","kartonDelivery":"","kartonGeliefert":"","parkzoneDatum":"","parkzoneGeliefert":"","klaviertransport":false,"klavierGross":"Nein","schwerTransport":"Kein","lampen":false,"lampenOrt":"Kein","lampenStueck":"0","einlagerung":false,"einlagerungPrice":"0","endreinigung":false,"bohrarbeit":false,"bohrarbeitPunkt":"0","entsorgung":false,"entsorgungType":"Normal","entsorgungM3":"0","aussenlift":"Nein","aussenliftStunde":"0","anschlussWaschmaschine":false,"sonstigeLeistung":"","sonstigePrice":""}',
      '', '', '', '', '', '',
      'Ueberweisung',
      '',
      '',
      '',
      '',
      '',
      '',
      'Gemeldet',
      'Niedrig',
      '',
      'pending',
      'unpaid',
      '',
      '',
      'Kunde',
      'محمحمحمح',
      0,
      'Bank and Bar',
      250000,
      200000,
      50000,
      1,
      250000,
      '',
      moveId,
    ],
  },
  {
    name: 'base_text_and_dates',
    sql: `UPDATE moves SET
      moveCode = ?,
      pickupAddress = ?,
      pickupFloor = ?,
      pickupElevatorCapacity = ?,
      pickupParkingDistance = ?,
      deliveryAddress = ?,
      deliveryFloor = ?,
      deliveryElevatorCapacity = ?,
      deliveryParkingDistance = ?,
      pickupDate = ?,
      deliveryDate = ?,
      volume = ?,
      grossPrice = ?,
      distance = ?,
      moveType = ?,
      anfahrt = ?
      WHERE id = ?`,
    params: [
      '60022',
      'Dorneburger str 1',
      '1.Etage',
      'Aufzug klein',
      '40 - 50 m',
      '24 Im Lörenkamp',
      '1.Etage',
      'Aufzug klein',
      '10 - 20 m',
      '2026-04-18 00:00:00',
      '2026-04-29 00:00:00',
      79,
      2500,
      400,
      'Umzug',
      0,
      moveId,
    ],
  },
  {
    name: 'services_and_notes',
    sql: `UPDATE moves SET
      servicesjson = ?,
      summary = ?,
      anmerkungen = ?,
      serviceanmerkungen = ?,
      moebelliste = ?,
      kundennote = ?,
      kontaktinfo = ?,
      zahlungsart = ?,
      rechnungnr = ?,
      bewertungplatform = ?,
      bewertunglink = ?,
      planstartzeit = ?,
      planendzeit = ?,
      planbemerkungen = ?,
      schadenstatus = ?,
      beschwerdeschweregrad = ?,
      extrabemerkungen = ?
      WHERE id = ?`,
    params: [
      '{"einpackservice":false,"einpackKartons":"0","abbauMoebeln":false,"abbauMoebelnM3":"0","abbauKueche":false,"abbauKuecheM3":"0","parkzoneAuszug":true,"auspackservice":false,"auspackKartons":"0","aufbauMoebeln":false,"aufbauMoebelnM3":"0","aufbauKueche":false,"aufbauKuecheM3":"0","parkzoneEinzug":true,"umzugskartons":"34","kleiderkartons":"34","kartonDelivery":"","kartonGeliefert":"","parkzoneDatum":"","parkzoneGeliefert":"","klaviertransport":false,"klavierGross":"Nein","schwerTransport":"Kein","lampen":false,"lampenOrt":"Kein","lampenStueck":"0","einlagerung":false,"einlagerungPrice":"0","endreinigung":false,"bohrarbeit":false,"bohrarbeitPunkt":"0","entsorgung":false,"entsorgungType":"Normal","entsorgungM3":"0","aussenlift":"Nein","aussenliftStunde":"0","anschlussWaschmaschine":false,"sonstigeLeistung":"","sonstigePrice":""}',
      '', '', '', '', '', '',
      'Ueberweisung',
      '',
      '',
      '',
      '',
      '',
      '',
      'Gemeldet',
      'Niedrig',
      '',
      moveId,
    ],
  },
  {
    name: 'status_and_audit',
    sql: `UPDATE moves SET
      status = ?,
      paymentStatus = ?,
      schaden_description = ?,
      beschwerde_description = ?,
      bezahlt_von = ?,
      betzhalkunde = ?,
      ist_bezahlt = ?,
      payment_way = ?,
      audit_total_price = ?,
      bank_betrag = ?,
      bar_betrag = ?,
      rechnung_ausgestellt = ?,
      rechnung_betrag = ?,
      rechnung_nummer = ?
      WHERE id = ?`,
    params: [
      'pending',
      'unpaid',
      '',
      '',
      'Kunde',
      'محمحمحمح',
      0,
      'Bank and Bar',
      250000,
      200000,
      50000,
      1,
      250000,
      '',
      moveId,
    ],
  },
];

const results = [];
for (const group of groups) {
  try {
    await connection.execute(group.sql, group.params);
    results.push({ name: group.name, ok: true });
  } catch (error) {
    results.push({
      name: group.name,
      ok: false,
      message: error.message,
      code: error.code,
      errno: error.errno,
      sqlState: error.sqlState,
      sqlMessage: error.sqlMessage,
    });
  }
}

console.log(JSON.stringify({ moveId, results }, null, 2));
await connection.end();
